name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel
          sudo apt-cache madison tesseract-ocr
          sudo apt -y install tesseract-ocr
          sudo apt-cache madison tesseract-ocr
