name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel
          sudo apt-cache madison tesseract-ocr
          sudo apt -y install tesseract-ocr libtesseract-dev libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config upx libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip libasound2-dev
          sudo apt-cache madison tesseract-ocr
